### ISSUE TITLE
Multibase SNPs counted as insertions

### ISSUE THREAD

**Issue by glennhickey** [jmonlong/sveval#10]
This variant out of `vg call` came up as as an 83bp INS false positive.  But it's really just a few point mutations.  Could `sveval` be changed to use a ref/alt delta as the insertion length? 
```
chr16	377919	12669_12677	CCCAGATGGAAAGGGCTGGAAGCCCCCGGGGACCCACCTGGAGATCTTGGCACACCAACTCTGACCTTGGCAAAGGTCACC	AGCCCAGATGGAAAGGGCTGGAAGCCCCCGGGGACCCACCTGGAGATCTTGGCACACCAACTCTGACCTTGGCAAAGGTCACG	13.3436	PASS	DP=13	GT:DP:AD:GL:GQ:GP:XD:MAD0/1:13:6,6:-2.89218,-2.1763,-2.89218:7:-1.37704:7.70605:6
```

**Comment by jmonlong** [comment]
Good idea, that would make more sense, I'll add this now.

**Comment by jmonlong** [comment]
I forgot to update this but sveval is now using the size delta as its size estimate (commit https://github.com/jmonlong/sveval/commit/92f69939ac982617b399b466406cc2a5784dece1).

In general, I'll try to update the mechanics to deal with variants that are not simple DEL/INS but involve long sequences in both the REF and ALT fields (like suggested in #11)
