### ISSUE TITLE
Snakefile's "envmodules" keyword is an unexpected keyword.

### ISSUE THREAD

**Issue by Robin-Rounthwaite** [jmonlong/sveval#19]
I set up my various directories as per https://github.com/jmonlong/sveval/tree/master/snakemake, I started the docker container, and  ran the snakemake command:
snakemake --configfile config.yaml --cores 4

But it appears that the recent addition of the envmodules keyword to rules is causing issues, because I received the following error message:
Unexpected keyword envmodules in rule definition

(There was one more line to the error message, describing that it was in line 38 of the Snakefile. Unfortunately, in a freak coincidence, my terminal screen froze on mustard halfway through copying the error message, and is refusing to reconnect. Thankfully, you're not missing out on much information beyond the line number in the other line. Sorry about that!)

Reverting to the following commit removed these issues:
commit 9f62fdab0568a9e8377b0b8ecdefdd11559cdd00
Author: Jean Monlong <jmonlong@ucsc.edu>
Date:   Wed Apr 19 09:15:18 2023 -0400

    Update README.md

**Comment by Robin-Rounthwaite** [comment]
Note that the docker container I used is the one in the current wiki:
docker run -it --rm -v `pwd`:/app -w /app -u `id -u $USER` quay.io/jmonlong/sveval:v2.2.0

**Comment by jmonlong** [comment]
I didn't realize that was a newer feature of snakemake. I've updated the docker container (same tag), so it should work now with that new commit too.

**Comment by Robin-Rounthwaite** [comment]
Thanks, Jean. The keywords are recognized now.
